/*
 * ========== keycodes ==========
 * Author: Sunil Sapkota
 * Description: These are all the keycodes provided by engine for inputs from
 * devices like keyboard, mouse, joystick, joystick-hat, gamepad, etc.
 */
#pragma once 

#include <GLFW/glfw3.h>

namespace Everest{

    /*Keyboard input codes*/
    enum Keycode {
        K_unknown         = GLFW_KEY_UNKNOWN,

        /* printable keys */
        K_space           = GLFW_KEY_SPACE,
        K_apostrophe      = GLFW_KEY_APOSTROPHE,
        K_comma           = GLFW_KEY_COMMA,
        K_minus           = GLFW_KEY_MINUS,
        K_period          = GLFW_KEY_PERIOD,
        K_slash           = GLFW_KEY_SLASH,
        K_0               = GLFW_KEY_0,
        K_1               = GLFW_KEY_1,
        K_2               = GLFW_KEY_2,
        K_3               = GLFW_KEY_3,
        K_4               = GLFW_KEY_4,
        K_5               = GLFW_KEY_5,
        K_6               = GLFW_KEY_6,
        K_7               = GLFW_KEY_7,
        K_8               = GLFW_KEY_8,
        K_9               = GLFW_KEY_9,
        K_semicolon       = GLFW_KEY_SEMICOLON,
        K_equal           = GLFW_KEY_EQUAL,
        K_a               = GLFW_KEY_A,
        K_b               = GLFW_KEY_B,
        K_c               = GLFW_KEY_C,
        K_d               = GLFW_KEY_D,
        K_e               = GLFW_KEY_E,
        K_f               = GLFW_KEY_F,
        K_g               = GLFW_KEY_G,
        K_h               = GLFW_KEY_H,
        K_i               = GLFW_KEY_I,
        K_j               = GLFW_KEY_J,
        K_k               = GLFW_KEY_K,
        K_l               = GLFW_KEY_L,
        K_m               = GLFW_KEY_M,
        K_n               = GLFW_KEY_N,
        K_o               = GLFW_KEY_O,
        K_p               = GLFW_KEY_P,
        K_q               = GLFW_KEY_Q,
        K_r               = GLFW_KEY_R,
        K_s               = GLFW_KEY_S,
        K_t               = GLFW_KEY_T,
        K_u               = GLFW_KEY_U,
        K_v               = GLFW_KEY_V,
        K_w               = GLFW_KEY_W,
        K_x               = GLFW_KEY_X,
        K_y               = GLFW_KEY_Y,
        K_z               = GLFW_KEY_Z,
        K_left_bracket    = GLFW_KEY_LEFT_BRACKET,
        K_backslash       = GLFW_KEY_BACKSLASH,
        K_right_bracket   = GLFW_KEY_RIGHT_BRACKET,
        K_tilde           = GLFW_KEY_GRAVE_ACCENT,

        /* function keys */
        K_escape          = GLFW_KEY_ESCAPE,
        K_enter           = GLFW_KEY_ENTER,
        K_tab             = GLFW_KEY_TAB,
        K_backspace       = GLFW_KEY_BACKSPACE,
        K_insert          = GLFW_KEY_INSERT,
        K_delete          = GLFW_KEY_DELETE,
        K_right           = GLFW_KEY_RIGHT,
        K_left            = GLFW_KEY_LEFT,
        K_down            = GLFW_KEY_DOWN,
        K_up              = GLFW_KEY_UP,
        K_page_up         = GLFW_KEY_PAGE_UP,
        K_page_down       = GLFW_KEY_PAGE_DOWN,
        K_home            = GLFW_KEY_HOME,
        K_end             = GLFW_KEY_END,
        K_caps_lock       = GLFW_KEY_CAPS_LOCK,
        K_scroll_lock     = GLFW_KEY_SCROLL_LOCK,
        K_num_lock        = GLFW_KEY_NUM_LOCK,
        K_print_screen    = GLFW_KEY_PRINT_SCREEN,
        K_pause           = GLFW_KEY_PAUSE,
        K_f1              = GLFW_KEY_F1,
        K_f2              = GLFW_KEY_F2,
        K_f3              = GLFW_KEY_F3,
        K_f4              = GLFW_KEY_F4,
        K_f5              = GLFW_KEY_F5,
        K_f6              = GLFW_KEY_F6,
        K_f7              = GLFW_KEY_F7,
        K_f8              = GLFW_KEY_F8,
        K_f9              = GLFW_KEY_F9,
        K_f10             = GLFW_KEY_F10,
        K_f11             = GLFW_KEY_F11,
        K_f12             = GLFW_KEY_F12,
        K_f13             = GLFW_KEY_F13,
        K_f14             = GLFW_KEY_F14,
        K_f15             = GLFW_KEY_F15,
        K_f16             = GLFW_KEY_F16,
        K_f17             = GLFW_KEY_F17,
        K_f18             = GLFW_KEY_F18,
        K_f19             = GLFW_KEY_F19,
        K_f20             = GLFW_KEY_F20,
        K_f21             = GLFW_KEY_F21,
        K_f22             = GLFW_KEY_F22,
        K_f23             = GLFW_KEY_F23,
        K_f24             = GLFW_KEY_F24,
        K_f25             = GLFW_KEY_F25,
        K_kp_0            = GLFW_KEY_KP_0,
        K_kp_1            = GLFW_KEY_KP_1,
        K_kp_2            = GLFW_KEY_KP_2,
        K_kp_3            = GLFW_KEY_KP_3,
        K_kp_4            = GLFW_KEY_KP_4,
        K_kp_5            = GLFW_KEY_KP_5,
        K_kp_6            = GLFW_KEY_KP_6,
        K_kp_7            = GLFW_KEY_KP_7,
        K_kp_8            = GLFW_KEY_KP_8,
        K_kp_9            = GLFW_KEY_KP_9,
        K_kp_decimal      = GLFW_KEY_KP_DECIMAL,
        K_kp_divide       = GLFW_KEY_KP_DIVIDE ,
        K_kp_multiply     = GLFW_KEY_KP_MULTIPLY,
        K_kp_subtract     = GLFW_KEY_KP_SUBTRACT,
        K_kp_add          = GLFW_KEY_KP_ADD,
        K_kp_enter        = GLFW_KEY_KP_ENTER,
        K_kp_equal        = GLFW_KEY_KP_EQUAL,
        K_left_shift      = GLFW_KEY_LEFT_SHIFT,
        K_left_control    = GLFW_KEY_LEFT_CONTROL,
        K_left_alt        = GLFW_KEY_LEFT_ALT,
        K_left_super      = GLFW_KEY_LEFT_SUPER,
        K_right_shift     = GLFW_KEY_RIGHT_SHIFT,
        K_right_control   = GLFW_KEY_RIGHT_CONTROL,
        K_right_alt       = GLFW_KEY_RIGHT_ALT ,
        K_right_super     = GLFW_KEY_RIGHT_SUPER,
        K_menu            = GLFW_KEY_MENU,

        K_last            = GLFW_KEY_LAST,
    };

    /*Mousebutton input codes*/
    enum MouseButton {
        MouseButton_0        = 0,
        MouseButton_left     = 0,

        MouseButton_1        = 1,
        MouseButton_right    = 1,

        MouseButton_2        = 2,
        MouseButton_middle   = 2,

        MouseButton_3        = 3,
        MouseButton_4        = 4,
        MouseButton_5        = 5,
        MouseButton_6        = 6,
        MouseButton_7        = 7,
    };

    /*Joystick input codes*/
    enum Joystick {
        Joystick_1  = GLFW_JOYSTICK_1 ,
        Joystick_2  = GLFW_JOYSTICK_2 ,
        Joystick_3  = GLFW_JOYSTICK_3 ,
        Joystick_4  = GLFW_JOYSTICK_4 ,
        Joystick_5  = GLFW_JOYSTICK_5 ,
        Joystick_6  = GLFW_JOYSTICK_6 ,
        Joystick_7  = GLFW_JOYSTICK_7 ,
        Joystick_8  = GLFW_JOYSTICK_8 ,
        Joystick_9  = GLFW_JOYSTICK_9 ,
        Joystick_10 = GLFW_JOYSTICK_10,
        Joystick_11 = GLFW_JOYSTICK_11,
        Joystick_12 = GLFW_JOYSTICK_12,
        Joystick_13 = GLFW_JOYSTICK_13,
        Joystick_14 = GLFW_JOYSTICK_14,
        Joystick_15 = GLFW_JOYSTICK_15,
        Joystick_16 = GLFW_JOYSTICK_16,
    };

    /*Joystick hat input codes*/
    enum JoystickHat {
        Hat_centered           = 0,
        Hat_up                 = 1,
        Hat_right              = 2,
        Hat_down               = 4,
        Hat_left               = 8,
        Hat_right_up           = (GLFW_HAT_RIGHT | GLFW_HAT_UP),
        Hat_right_down         = (GLFW_HAT_RIGHT | GLFW_HAT_DOWN),
        Hat_left_up            = (GLFW_HAT_LEFT  | GLFW_HAT_UP),
        Hat_left_down          = (GLFW_HAT_LEFT  | GLFW_HAT_DOWN),
    };

    /*Gamepad input codes*/
    enum Gamepad {
        Gamepad_a                   = GLFW_GAMEPAD_BUTTON_A,
        Gamepad_b                   = GLFW_GAMEPAD_BUTTON_B,
        Gamepad_x                   = GLFW_GAMEPAD_BUTTON_X,
        Gamepad_y                   = GLFW_GAMEPAD_BUTTON_Y,
        Gamepad_left_bumper         = GLFW_GAMEPAD_BUTTON_LEFT_BUMPER,
        Gamepad_right_bumper        = GLFW_GAMEPAD_BUTTON_RIGHT_BUMPER,
        Gamepad_back                = GLFW_GAMEPAD_BUTTON_BACK,
        Gamepad_start               = GLFW_GAMEPAD_BUTTON_START,
        Gamepad_guide               = GLFW_GAMEPAD_BUTTON_GUIDE,
        Gamepad_left_thumb          = GLFW_GAMEPAD_BUTTON_LEFT_THUMB,
        Gamepad_right_thumb         = GLFW_GAMEPAD_BUTTON_RIGHT_THUMB,
        Gamepad_dpad_up             = GLFW_GAMEPAD_BUTTON_DPAD_UP,
        Gamepad_dpad_right          = GLFW_GAMEPAD_BUTTON_DPAD_RIGHT,
        Gamepad_dpad_down           = GLFW_GAMEPAD_BUTTON_DPAD_DOWN,
        Gamepad_dpad_left           = GLFW_GAMEPAD_BUTTON_DPAD_LEFT,
        Gamepad_last                = GLFW_GAMEPAD_BUTTON_LAST,

        Gamepad_cross               = GLFW_GAMEPAD_BUTTON_A,
        Gamepad_circle              = GLFW_GAMEPAD_BUTTON_B,
        Gamepad_square              = GLFW_GAMEPAD_BUTTON_X,
        Gamepad_triangle            = GLFW_GAMEPAD_BUTTON_Y,

        Gamepad_axis_left_x         = 0,
        Gamepad_axis_left_y         = 1,
        Gamepad_axis_right_x        = 2,
        Gamepad_axis_right_y        = 3,
        Gamepad_axis_left_trigger   = 4,
        Gamepad_axis_right_trigger  = 5,
    };
}
